name: techtag
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  flutter_svg: ^1.1.5
  just_the_tooltip: ^0.0.12
  dio: ^4.0.6
  cached_network_image: ^3.2.2
  carousel_slider: ^4.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies: 
  flutter_lints: ^1.0.0
  lints: 1.0.0
  hive_generator: ^1.1.2
  build_runner: ^2.1.7
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - "assets/icons/"

